import Image from "next/image";
import { JournalEntry } from "@/app/types/journal";

interface MediaSectionProps {
  entry: JournalEntry | null;
  content: string;
  isGenerating: boolean;
  onGenerate: () => void;
}

export default function MediaSection({
  entry,
  content,
  isGenerating,
  onGenerate,
}: MediaSectionProps) {
  return (
    <div className="mb-6">
      <button
        onClick={onGenerate}
        disabled={isGenerating || !content.trim()}
        className="w-16 h-16 bg-gradient-to-br from-purple-600 to-pink-600 text-white rounded-lg shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none flex items-center justify-center font-bold text-lg"
        title="Generate cinematic moment for this day"
      >
        {isGenerating ? "⏳" : "🎬"}
      </button>

      {entry?.visualPrompt && (
        <div className="mt-4 space-y-4">
          {/* Generated Image */}
          {entry.mediaUrl && (
            <div className="relative rounded-lg overflow-hidden border-2 border-purple-200 dark:border-purple-800 shadow-lg">
              <Image
                src={entry.mediaUrl}
                alt="Generated cinematic scene"
                width={400}
                height={200}
                className="w-full h-48 object-cover"
                unoptimized={true}
                onError={(e) => {
                  e.currentTarget.style.display = "none";
                }}
              />
              <div className="absolute top-2 right-2 bg-black/70 text-white text-xs px-2 py-1 rounded">
                Generated by FLUX.2 Klein
              </div>
            </div>
          )}

          {/* Visual Prompt Details */}
          <div className="p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg border border-purple-200 dark:border-purple-800">
            <h3 className="text-sm font-semibold text-purple-800 dark:text-purple-200 mb-2">
              Cinematic Vision
            </h3>
            <p className="text-sm text-purple-700 dark:text-purple-300 mb-2">
              <strong>Scene:</strong> {entry.visualPrompt.visualPrompt}
            </p>
            <div className="flex flex-wrap gap-2 text-xs">
              <span className="bg-purple-100 dark:bg-purple-800 text-purple-800 dark:text-purple-200 px-2 py-1 rounded">
                {entry.visualPrompt.mood}
              </span>
              <span className="bg-purple-100 dark:bg-purple-800 text-purple-800 dark:text-purple-200 px-2 py-1 rounded">
                {entry.visualPrompt.colorPalette}
              </span>
              <span className="bg-purple-100 dark:bg-purple-800 text-purple-800 dark:text-purple-200 px-2 py-1 rounded">
                {entry.visualPrompt.cinematicStyle}
              </span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
